extends SceneTree
const Model = preload("res://redesign/model.gd")
const Content = preload("res://redesign/content.gd")
const Forecast = preload("res://redesign/forecast.gd")
const Data = preload("res://redesign/samples/risk_sample_data.gd")
var checks := 0
var failures := 0
var evidence: Array = []

func check(ok: bool, message: String) -> void:
	checks += 1
	if not ok:
		failures += 1
		print("FAIL: " + message)

func _initialize() -> void:
	_run.call_deferred()

func sample(index: int, hot: bool) -> RefCounted:
	var model = Model.new()
	Data.seed_model(model, index)
	for id in Data.initial_plan(hot): check(model.load_round(id), "load owned " + id)
	return model

func dummy(gun: String = "single") -> RefCounted:
	var model = Model.new()
	Data.seed_model(model, 1)
	model.s.gun = gun
	model.s.enemies = [{"kind": "wall", "name": "시험 표적", "hp": 100, "max_hp": 100, "def": 0, "speed": 1, "distance": 30, "burn": 0, "lane": 0}]
	model.s.encounter_total = 1
	model.s.deployed = 1
	return model

func _run() -> void:
	if not ProjectSettings.globalize_path("user://").replace("\\", "/").contains("/qa_runtime/ammo_risk/"):
		print("FAIL: isolated user directory required")
		quit(1)
		return
	for index in range(2):
		for hot in [false, true]:
			var model = sample(index, hot)
			check(Model.new().restore_state(model.s), "valid owned sample state")
			var before := JSON.stringify(model.s)
			var prediction := Forecast.analyze(model.s, true, true)
			check(JSON.stringify(model.s) == before, "forecast does not mutate live state")
			check(int(model.s.reload_heat) == 0 and model.reload_cost() == 1, "planning has no heat debt")
			check(model.confirm() and model.fire(), "real firing accepted")
			check(model.s.enemies == prediction.enemies and model.s.phase == prediction.phase, "firing forecast matches live resolver")
			var firing_phase := str(model.s.phase)
			var fire_hp: Array = model.s.enemies.map(func(e): return e.hp)
			var projected: Dictionary = prediction.reload
			if model.s.phase == "ready":
				check(int(model.s.reload_heat) == (1 if hot else 0), "heat generated by fired variant")
				check(Model.new().restore_state(JSON.parse_string(JSON.stringify(model.s))), "pending heat save round trip")
				check(model.reload_cost() == projected.cost, "reload preview cost")
				var turn_before := int(model.s.turns)
				check(model.reload_magazine(), "real reload accepted")
				check(model.s.enemies == projected.enemies and model.s.phase == projected.phase, "reload preview includes exact resulting enemies and phase")
				check(int(model.s.turns) - turn_before == projected.turns, "actual elapsed reload time")
				check(model.s.reload_heat == 0, "reload settles heat")
				check(Model.new().restore_state(model.s), "post reload save valid")
			if index == 0:
				check(firing_phase == ("ready" if hot else "lost"), "urgent case: higher output averts contact")
			else:
				check(fire_hp[0] == (3 if hot else 5), "barrier reduces high-output benefit")
				check(model.s.phase == ("lost" if hot else "plan"), "shield case: fast reload preserves a next action")
			evidence.append({"case": index, "hot": hot, "after_fire_hp": fire_hp, "after_fire_phase": firing_phase, "reload": projected})
	for gun in Content.GUNS:
		var model = dummy(gun)
		for id in ["charge_hot", "precise", "pierce"]: check(model.load_round(id), "gun legal load " + gun)
		var before := JSON.stringify(model.s)
		var predicted := Forecast.analyze(model.s, true, true)
		check(JSON.stringify(model.s) == before, "gun forecast purity " + gun)
		check(model.confirm() and model.fire(), "gun fires " + gun)
		check(model.s.reload_heat == 1, "one fired hot round " + gun)
		var cost: int = model.reload_cost()
		check(cost == int(Content.GUNS[gun].reload) + 1, "gun base cost plus heat " + gun)
		if gun == "amplifier":
			check(model.s.magazine.size() == 2 and int(model.s.buff.dmg) == 8, "amplifier stops on survivor and doubles boost")
			check(model.fire() and model.s.reload_heat == 1, "heat survives another amplifier action")
		else:
			check(model.reload_magazine(), "gun reload " + gun)
			if gun == "scatter":
				check(predicted.reload.cost_min == cost and predicted.reload.cost_max == cost, "scatter exact reload range for one enemy")
				check(predicted.reload.lost_probability == 0.0, "scatter surviving reload probability")
			else: check(model.s.enemies == predicted.reload.enemies, "gun full reload outcome " + gun)
	_test_edges()
	_test_random()
	var file := FileAccess.open(OS.get_environment("QA_OUTPUT_DIR").path_join("risk_rules.json"), FileAccess.WRITE)
	file.store_string(JSON.stringify({"checks": checks, "failures": failures, "scenarios": evidence}, "\t"))
	file.close()
	print("AMMO RISK RULES COMPLETE checks=%d failures=%d" % [checks, failures])
	quit(0 if failures == 0 else 1)

func _test_edges() -> void:
	var model = dummy()
	var legacy: Dictionary = model.s.duplicate(true)
	legacy.erase("reload_heat")
	var restored = Model.new()
	check(restored.restore_state(legacy) and restored.reload_cost() == 1, "old v8 without heat remains loadable")
	for corrupt in [-1, 0.5, "1", true, 1000001]:
		var candidate: Dictionary = legacy.duplicate(true)
		candidate.reload_heat = corrupt
		var original := JSON.stringify(restored.s)
		check(not restored.restore_state(candidate) and JSON.stringify(restored.s) == original, "reject invalid heat without replacing live state")
	model.load_round("charge_hot")
	check(model.undo(), "remove pending hot round")
	check(model.reload_cost() == 1, "removing plan has no cost")
	model.load_round("charge_hot")
	model.confirm()
	model.reload_magazine()
	check(model.s.turns == 1 and model.s.reload_heat == 0, "discard unfired hot round without thermal cost")
	model = dummy()
	model.s.deck[0] = "charge_hot"
	model.s.hand[0] = "charge_hot"
	for id in ["charge_hot", "charge_hot", "precise", "pierce"]: model.load_round(id)
	model.confirm()
	model.fire()
	check(model.s.reload_heat == 2 and model.reload_cost() == 3, "two fired hot rounds accumulate")
	check(Content.source_id("charge_hot") == "charge" and Content.compressed_id("charge_hot").is_empty(), "same ammo family without accidental compression")
	model.begin_encounter()
	check(model.s.reload_heat == 0, "new encounter resets heat")
	model = dummy()
	model.s.enemies[0].hp = 1
	for id in ["precise", "charge_hot"]: model.load_round(id)
	model.confirm()
	model.fire()
	check(model.s.phase == "reward" and model.s.shots == 1 and model.s.reload_heat == 0, "unfired hot round behind final kill incurs no heat")
	model = dummy()
	model.s.enemies[0].hp = 2
	model.load_round("charge_hot")
	model.confirm()
	model.fire()
	check(model.s.phase == "reward" and model.s.reload_heat == 0 and model.s.history.back().detail.results[0].heat_added == 1, "finishing shot records heat but no post-combat tax")
	model = dummy("burst")
	model.s.equipped_parts = ["loader", "afterburner", "inferno"]
	model.load_round("charge_hot")
	model.confirm()
	model.fire()
	check(model.base_reload_cost() == 3 and model.reload_cost() == 4, "existing reload parts and heat compose")
	model = dummy()
	model.s.enemies[0].hp = 5
	model.s.enemies[0].distance = 2
	model.s.enemies[0].burn = 5
	model.load_round("charge_hot")
	model.confirm()
	model.fire()
	var burn_reload := Forecast.reload_now(model.s)
	check(burn_reload.phase == "reward", "burn can end encounter before movement during hot reload")
	model = dummy()
	model.load_round("charge_c") # Not owned: ensure variant is not silently interchangeable.
	check(model.s.plan.is_empty(), "compressed variants retain inventory identity")
	check(Content.heat_cost("charge_c") == 0 and Content.heat_cost("charge_f") == 0, "compression does not gain an extra thermal penalty")
	model = dummy()
	var caster := Data._enemy("caster", 100, 0, 1, 30, 0)
	caster.merge({"charge": 0, "charge_max": 3, "charge_pull": 2})
	model.s.enemies = [caster, Data._enemy("runner", 100, 0, 2, 20, 1)]
	model.s.encounter_total = 2
	model.s.deployed = 2
	model.load_round("charge_hot")
	model.confirm()
	model.fire()
	var charge_reload := Forecast.reload_now(model.s)
	model.reload_magazine()
	check(model.s.enemies == charge_reload.enemies and model.s.enemies[1].distance == 12, "extra reload tick triggers support pull and movement")
	model = dummy()
	model.s.enemies[0].stance = true
	model.s.enemies[0].stance_closed = true
	model.s.enemies[0].stance_def = 4
	model.s.enemies[0].def = 4
	model.load_round("charge_hot")
	model.confirm()
	model.fire()
	var stance_reload := Forecast.reload_now(model.s)
	model.reload_magazine()
	check(model.s.enemies == stance_reload.enemies and model.s.enemies[0].def == 0, "two thermal reload ticks preserve armor phase parity")
	model = dummy()
	model.s.enemies[0].hp = 2
	model.s.reinforcements = [Data._enemy("runner", 6, 0, 2, 4, 1)]
	model.s.encounter_total = 2
	model.load_round("charge_hot")
	var reserve_prediction := Forecast.analyze(model.s, true, true)
	model.confirm()
	model.fire()
	check(model.s.reload_heat == 1 and model.s.enemies.size() == 2, "clearing front wave does not clear debt before reserves")
	model.reload_magazine()
	check(model.s.phase == "lost" and model.s.enemies == reserve_prediction.reload.enemies, "reload prediction includes newly deployed enemy contact")

func _test_random() -> void:
	var model = dummy("scatter")
	model.s.enemies.append(Data._enemy("runner", 12, 0, 2, 20, 1))
	model.s.encounter_total = 2
	model.s.deployed = 2
	for id in ["charge_hot", "precise", "pierce"]: model.load_round(id)
	var prediction := Forecast.analyze(model.s, true, true)
	check(prediction.random and prediction.reload.random, "scatter reload explicitly reports ranges")
	var initial: Dictionary = model.s.duplicate(true)
	for seed_value in range(32):
		var actual = Model.new()
		actual.s = initial.duplicate(true)
		var rng := RandomNumberGenerator.new()
		rng.seed = seed_value
		actual.s.target_rng_state = str(rng.state)
		actual.confirm()
		actual.fire()
		var cost := actual.reload_cost()
		actual.reload_magazine()
		check(cost >= prediction.reload.cost_min and cost <= prediction.reload.cost_max, "scatter cost in predicted range")
		for entry in prediction.reload.enemies:
			var enemy: Dictionary = actual.s.enemies[entry.target]
			check(enemy.hp >= entry.hp_min and enemy.hp <= entry.hp_max, "scatter HP in predicted range")
			check(enemy.distance >= entry.distance_min and enemy.distance <= entry.distance_max, "scatter distance in predicted range")
	var debt: Dictionary = initial.duplicate(true)
	debt.reload_heat = 1
	var other := Forecast.analyze(debt, true, true)
	check(other.reload.cost_min == prediction.reload.cost_min + 1, "forecast cache distinguishes outstanding heat")
